apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mysql
    server: nfs01
