apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: wordpress
  name: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31004
    targetPort: 80
  selector:
    run: wordpress
  type: NodePort
status:
  loadBalancer: {}
